### ISSUE TITLE
CSS Problems

### ISSUE THREAD

**Issue by doublemarked** [funkjedi/acf-qtranslate#3]
Hello,

Thanks for this plugin. It's exactly what we need!

On Wordpress 3.8.1, the labels & language selection tabs on textareas overlap the textarea content. I am not sure if this happens on any previous version of Wordpress. I added the following CSS overrides to accommodate this problem,

``` css
.multi-language-field { 
  margin-top: 0px;
}
.repeater .multi-language-field { 
  margin-top: 32px;
}
.multi-language-field .wp-switch-editor {
    top: -32px;
}
```

I'm not submitting a pull request because I'm not familiar with how this would affect other versions of Wordpress. I trust Mr. funkjedi will know what is best.
